# syntax = docker/dockerfile:1

ARG RUBY_VERSION=3.4.6-slim-bookworm
FROM docker.io/library/ruby:$RUBY_VERSION

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    curl \
    git \
    sqlite3 \
    libyaml-dev \
    libffi-dev \
    zlib1g-dev \
    libssl-dev \
    pkg-config && \
    curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install --no-install-recommends -y nodejs && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install

ENV PATH="/usr/local/bundle/bin:$PATH"

COPY . .

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]